### ISSUE TITLE
Logowanie: wyjście z okna, albo cofnięcie

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#14]
Nie da się nic zrobić poza stworzeniem konta.
A co jeśli user wszedł tu przez przypadek?
Myślę, że warto dodać taką możliwość, np. na logu aplikacji.
Wtedy:
 StworzKonto->ClickOnAbituriaLogo->MamKonto.
Oprócz braku możliwości stworzenia konta bez nazwy, nie można również stworzyć go po dodaniu spacji jako nazwy, a także istnieje ograniczenie liczby znaków w nazwie. User o tym nic nie wie, chyba że zrobi źle. Czy tak ma być?

**Comment by astolowska** [comment]
User nie ma możliwości wejść w to okno inaczej, niż otwierając aplikację, jest to niemożliwe. Przy każdorazowym otwarciu Abiturii (zaznaczam, że programu, a nie okna głównego) musi się zalogować, tak działa system - powinno być jasnym, do jakiego pliku spisywać dane o postępach. Z tego powodu nie jest zalecanym dać użytkownikowi jakiejkolwiek drogi obejścia logowania, bo może go to wykluczyć z zapisu info.  Jasne, w przypadku nie zalogowania się postępy mogą być zapisywane na defaultowym koncie Maturzysty, ale może to doprowadzić do sytuacji, gdy user zapomni się przelogować pomimo chęci, albo nie jest pewien tego, na którym koncie jest zalogowany, co będzie owocowało rozbiciem jego zapisu na kilka kont, wszędzie niepełnym. 
Użytkownik nie musi tworzyć konta każdorazowo, wystarczy, że zaloguje się na istniejące i może normalnie obcować z programem. 

Logowanie jest tak naprawdę tylko podkładką pod zapis o wykonanych zadaniach i podanych rozwiązaniach, co zaimplementuję w kolejnych dniach. 

Jeżeli chodzi o nazwę, wydawały mi się to dość sensowne ograniczenia, które zabezpieczają program przed userem. Oczywiście nie widzę problemu w zamieszczeniu o nich informacji w tekście wyżej, tak jak o ograniczeniu ilości kont. Raz jeszcze, jest to zabezpieczenie dla sprawnego działania programu. 

Jeżeli ten system nie jest intuicyjny lub wydaje się być wadliwy, proszę o dalsze sugestie jego poprawy.

**Comment by haribo841** [comment]
Chodzi mi o sytuację gdy mam konto i pomylę się przy klikaniu guzika. Zamiast "zaloguj" wybiorę "stwórz". Nie mam jak się cofnąć. Podpięcie drugiej opcji pod logo wyeliminowałoby ten problem. Okno jest głównie puste i dodanie treści o zasadach tworzenia nazwy nie są dla mnie złym pomysłem, na jego sensowne wypełnienie.

**Comment by astolowska** [comment]
Jasne, teraz rozumiem problem lepiej - przy następnej iteracji programu zaimplementuję przycisk cofania.

**Comment by haribo841** [comment]
Logo przechodzi do Main, trzeba zmienić na zwykły przycisk cofnij do logowania/stworzenia.

**Comment by haribo841** [comment]
![image](https://user-images.githubusercontent.com/48011447/147506567-2ade0252-a93d-461f-9554-6184daa30bb4.png)
Zamyka okno i odpala je jeszcze raz, nie cofa. Przez to występuje takie mignięcie okna. Tak ma być?

**Comment by astolowska** [comment]
Tak ma być. To jest window, nawigacja stron tu nie działa, do tego potrzebny jest frame. Do momentu, gdy nie uda się zmodyfikować struktury, to jest najlepsze rozwiązanie. Bez tego zawartość  otworzyłaby się w nowym oknie, ale stare by zostało.
