### ISSUE TITLE
Logowanie: Wyświetlania zalogowanego użytkownika na stronie głównej

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#15]
Obecnie wartość po zalogowaniu użytkownika jest pusta.
Komunikat "witaj, " powinien mieć po przecinku nazwę użytkownika.

**Comment by astolowska** [comment]
Tak jest, pracuję nad tym, powinno działać przed kolejnymi zajęciami, będę informować na bieżąco.

**Comment by astolowska** [comment]
Opóźniło się, ale rozwiązanie planowane jest w następnej iteracji
