### ISSUE TITLE
Usuń lub wypełnij ten blok kodu.

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#18]
Warning S108. Either remove or fill this block of code.

Zagnieżdżone bloki kodu nie powinny być puste. Daj to do ifa i wywal elsa.

W większości przypadków blok kodu jest pusty, gdy naprawdę brakuje fragmentu kodu. Więc taki pusty blok musi być albo wypełniony, albo usunięty.

Przykład kodu niezgodnego:
`for (int i = 0; i < 42; i++){} // Celowo pusty lub brakujący fragment kodu`
Wyjątki:
Gdy blok zawiera komentarz, ten blok nie jest uważany za pusty.
Linijki:
135, 176, 182, 187, 202, 207, 222, 227, 243, 248, 264, 269, 285, 290, 304, 309, 328, 333, 349, 354, 370, 375, 393, 398, 406, 420, 425, 440, 445, 463, 482, 483, 518, 532, 551, 586, 607, 626, 627, 662, 676, 695, 696, 739, 753, 762, 771, 780, 787, 808, 813, 849, 863, 951, 977, 982, 1057.
![image](https://user-images.githubusercontent.com/48011447/144759062-46812314-b952-44f0-a3cf-0dddbfbb0112.png)

**Comment by Filippo1998r** [comment]
okej, ale nie zawsze tak to działa, w danym przypadku poprawię, ale często też kolejność warunków ma znaczenie i wydaje mi się że takie podejście mogłoby komplikować. Ale zerknę przy czasie na pozostałe przypadki. Swoją drogą, czy to program wynajduje te błędy, bo takie maszynowe podejście trochę widzę xD

**Comment by haribo841** [comment]
Tak, pisałem o tym tutaj: https://github.com/Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski/discussions/10#discussioncomment-1748776

**Comment by haribo841** [comment]
Po poprawce zamiast to wyeliminować, to dopisałeś jeszcze jeden taki przypadek.

**Comment by astolowska** [comment]
Porób sobie kilka takich niedokończonych warunków więcej i spróbuj sprawnie działać, zobaczysz, jak mieli. Dobre praktyki nie są po to, by się czepiać, tylko aby nie sabotować roboty innym.
