### ISSUE TITLE
Zamiast tego użyj przeciwnego operatora ('!=')

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#19]
Warning S1940. Use the opposite operator ('!=') instead.

Kontrole logiczne nie powinny być odwracane.

Odwrócenie wyniku porównania logicznego jest niepotrzebnie skomplikowane. Zamiast tego należy dokonać odwrotnego porównania.

Przykład kodu niezgodnego:
```
if ( !(a == 2)) { ...} // Niezgodny
bool b = !(i < 10); // Niezgodny
```
Zgodne rozwiązanie:
```
if (a != 2) { ...}
bool b = (i >= 10);
```
Linijki:
519 x3, 587 x3, 663 x3, 740 x3, 788 x3, 850 x3, 952 x4.
![image](https://user-images.githubusercontent.com/48011447/144758858-cd582c18-3479-46f1-ba92-eadb7d097dfa.png)

**Comment by Filippo1998r** [comment]
okej, dzięki, po prostu odbierałem to inaczej czyli zanegowanie całego wyrażenia w różnych wypadkach było dla mnie bezpieczniejsze niż negowanie konkretnej wartości w wyrażeniach

**Comment by Filippo1998r** [comment]
Pytanie tylko: czy to powoduje jakieś błędy?

**Comment by haribo841** [comment]
Jest to pomniejsza zła praktyka kodowania. Dla większości != jest dużo czytelniejsze, niż !(czasami_dlugi_warunek == "...")
Nie wiem gdzie i w jaki sposób to zwiększa bezpieczeństwo. Tam właśnie negujesz wartości w wyrażeniach wykrzyknikiem.
To jak, poprawisz?

**Comment by astolowska** [comment]
> okej, dzięki, po prostu odbierałem to inaczej czyli zanegowanie całego wyrażenia w różnych wypadkach było dla mnie bezpieczniejsze niż negowanie konkretnej wartości w wyrażeniach

https://realpython.com/python-is-identity-vs-equality/#comparing-equality-with-the-python-and-operators
