### ISSUE TITLE
Usuń ten zakomentowany kod

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#20]
Warning S125. Remove this commented out code.

Takich sekcji kodu nie należy komentować.

Programiści nie powinni komentować kodu, ponieważ rozpycha on programy i zmniejsza czytelność.
Nieużywany kod należy usunąć i w razie potrzeby można go pobrać z historii kontroli źródła.

Linijki:
27, 34, 71, 766, 1047, 1051, 1070, 1530, 2298.
![image](https://user-images.githubusercontent.com/48011447/144759041-a07a7962-5225-49cb-b6ae-ce61945c462e.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
![image](https://user-images.githubusercontent.com/48011791/145722742-56c2181c-df39-4549-b0a5-03acf3721bd5.png)
2-3 linijek bym się akurat nie czepiała, zwłaszcza gdy mają to być często wykorzystywane funkcje (jak ta tutaj, do przenoszenia wartości). Normalna sprawa. Zgadzam się, że problemem jest np. kod na switcha, który zajmuje kilkanaście-kilkadziesiąt linijek nie robiących nic, bo nie był chyba ani razu używany.

**Comment by haribo841** [comment]
Zgadzam się, nieadekwatne zdjęcie i doczepienie się, chodziło mi głównie o pięknego switcha. ![image](https://user-images.githubusercontent.com/48011447/145722833-cbcddcfa-c9be-4aac-9346-200315a81d32.png)
Zaszła pomyłka, błąd zrobiony z rozpędu, zawsze brałem ostatni przykład wystąpienia.

**Comment by Filippo1998r** [comment]
tak, ja wiem nawet przed przeczytaniem tej kwestii już tego switcha usunąłem bo denerwowau 😄
