### ISSUE TITLE
Połącz tę gałąź z identyczną w linii wcześniej lub zmień jedną z implementacji

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#21]
Warning S1871. Either merge this branch with the identical one on previous line or change one of the implementations.

Posiadanie dwóch przypadków w tej samej instrukcji _switch_ lub gałęziach w tej samej strukturze _if_ z tą samą implementacją jest w najlepszym przypadku zduplikowanym kodem, a w najgorszym błędem kodowania. Jeśli ta sama logika jest naprawdę potrzebna dla obu instancji, to w strukturze _if_ powinny być one połączone lub w przypadku przełącznika jedna powinna przejść do drugiej.

Przykład kodu niezgodnego:
```
switch (i)
{
  case 1:
    DoFirst();
    DoSomething();
    break;
  case 2:
    DoSomethingDifferent();
    break;
  case 3:  // Niezgodny; powiela wdrożenie przypadku 1
    DoFirst();
    DoSomething();
    break;
  default:
    DoTheRest();
}

if (a >= 0 && a < 10)
{
  DoFirst();
  DoTheThing();
}
else if (a >= 10 && a < 20)
{
  DoTheOtherThing();
}
else if (a >= 20 && a < 50)   // Niezgodny; duplikuje pierwszy warunek
{
  DoFirst();
  DoTheThing();
}
```
Wyjątki:
Bloki w łańcuchu _if_, które zawierają jeden wiersz kodu, są ignorowane, podobnie jak bloki w instrukcji _switch_, które zawierają pojedynczy wiersz kodu z następującą instrukcją _break_ lub bez niej.
```
if (a >= 0 && a < 10)
{
  DoTheThing();
}
else if (a >= 10 && a < 20)
{
  DoTheOtherThing();
}
else if (a >= 20 && a < 50)    //nie ma problemu, zwykle robi się to celowo, aby zwiększyć czytelność
{
  DoTheThing();
}
```
Ale ten wyjątek nie dotyczy łańcuchów _if_ bez _else_ lub _switch_ bez klauzul _default_, gdy wszystkie gałęzie mają ten sam pojedynczy wiersz kodu. W przypadku łańcuchów _if_ z _else_ lub _switch_ z klauzulami _default_, reguła {rule:csharpsquid:S3923} zgłasza błąd.
```
if(a == 1)
{
  doSomething();  //Niezgodne, mogło to zostać zrobione celowo, ale prawdopodobnie tak nie jest
}
else if (a == 2)
{
  doSomething();
}
```
Linijki:
1123 z 1142, 473 z 485, 542 z 553, 617 z 629, 686 z 698, 869 z 896, 890 z 946, 924 z 934, 968 z 973.
![image](https://user-images.githubusercontent.com/48011447/144759403-7f1c7ecf-ff56-4bb7-bef8-70ff9e0aca18.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian. Jest tu nawet prościej, niż w przypadku #31, bo nawet nie używasz funkcji, ale rozwiązanie mogłoby być podobne.

**Comment by astolowska** [comment]
Mówiliśmy o tym od początku, przynajmniej kilkadziesiąt if-ów można było zastąpić switchem, występuje bardzo dużo powtórzeń. Byłoby dla ciebie elastyczniej i dużo wygodniej działać na określonych, dobrze napisanych warunkach, niż zmieniać te same wartości w przypadku ich każdego, wielokrotnego wystąpienia.
