### ISSUE TITLE
Metody nie powinny być puste

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#22]
Warning S1186. Dodaj zagnieżdżony komentarz wyjaśniający, dlaczego ta metoda jest pusta, zgłoś „NotSupportedException” lub zakończ implementację.

Istnieje kilka powodów, dla których metoda nie ma treści metody:

- Jest to niezamierzone pominięcie i należy je naprawić.
- Nie jest jeszcze lub nigdy nie będzie wspierany. W takim przypadku należy zgłosić _NotSupportedException_.
- Metoda jest celowo pustym nadpisaniem. W takim przypadku zagnieżdżony komentarz powinien wyjaśniać przyczynę nadpisania pustego miejsca.

Przykład kodu niezgodnego:
```
public override void DoSomething()
{
}

public override void DoSomethingElse()
{
}
```
Zgodne rozwiązanie:

```
public override void DoSomething()
{
  // Nie rób nic z powodu X i Y.
}

public override void DoSomethingElse()
{
  throw new NotSupportedException();
}
```
Wyjątki:
Następujące metody są ignorowane:

- puste metody (virtual) wirtualne,
- puste metody, które zastępują metodę (abstract) abstrakcyjną,
- puste nadpisania w zespołach testowych (test assemblies).

Linijka: 1078
![image](https://user-images.githubusercontent.com/48011447/144759763-749242d9-4c4a-4a29-8d32-61bcdff7e191.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
Faktycznie dobrze dać komentarz, jeżeli na razie nie będziesz z tego korzystał. Czasem zrobi się funkcję zawczasu, wiadomo, ale łatwiej nie zgubić się w kodzie rozpisując, co zamierzasz tam później umieścić.
