### ISSUE TITLE
Nieużywane zmienne lokalne należy usunąć

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#24]
Warning S1481. Usuń nieużywaną zmienną lokalną „wartosc”.

Komunikat IDE0059. Niepotrzebne przypisanie wartości do 'wartosc'.

Pomijam już, że część jest nazywana po angielsku, a część po polsku i takie nazewnictwo nie jest systematyczne.
Nie dość, że nigdy i nigdzie nie używasz zmiennej wartość, to jeszcze dałeś typ var jak używasz tego tylko do liczb całkowitych.
Jeśli zmienna lokalna jest zadeklarowana, ale nie jest używana, jest to martwy kod i należy ją usunąć. Poprawi to łatwość utrzymania, ponieważ programiści nie będą się zastanawiać, do czego służy zmienna.

Przykład kodu niezgodnego:
```
public int NumberOfMinutes(int hours)
{
  int seconds = 0;   // sekundy nigdy nie są używane
  return hours * 60;
}
```
Zgodne rozwiązanie:
```
public int NumberOfMinutes(int hours)
{
  return hours * 60;
}
```
Wyjątki:
Niewykorzystane zasoby utworzone lokalnie w instrukcji _using_ nie są zgłaszane.
```
using(var t = new TestTimer()) // t nigdy nie jest używany, ale jest zgodny.
{
  //...
}
```
Linijka: 1046
![image](https://user-images.githubusercontent.com/48011447/144760134-e438c39d-07a4-4dc7-b6a5-a71f5c97e921.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
Problem deklarowania nieużywanych zmiennych lub pustych funkcji, jak również niedokańczania kodu warunkowego jest poruszany także w innych tematach.

**Comment by astolowska** [comment]
Every parameter in a method call forces the programmer reading it to figure out what information is found in this parameter. And if a parameter is entirely unused in the method body, this “noggin scratching” is for naught.

And in any case, additional parameters are extra code that has to be run.

Sometimes we add parameters with an eye to the future, anticipating changes to the method for which the parameter might be needed. All the same, experience shows that it’s better to add a parameter only when it’s genuinely needed. After all, anticipated changes often remain just that—anticipated.
