### ISSUE TITLE
Usuń tę pustą instrukcję

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#25]
Warning S1116. Remove this empty statement.

Puste oświadczenia należy usunąć.

Puste instrukcje, tj. ;, są zwykle wprowadzane przez pomyłkę, na przykład dlatego, że:

- Miało to zostać zastąpione prawdziwym stwierdzeniem, ale zapomniano o tym.
- Była literówka, która spowodowała podwojenie średnika, czyli ;;.

Przykład kodu niezgodnego:
```
void DoSomething()
{
    ; // Niezgodny – był używany jako rodzaj znacznika TODO, WIP, itp, itd.
}

void DoSomethingElse()
{
    Console.WriteLine("Hello, world!");;  // Niezgodny - podwójny średnik
    // ...
    // Rzadko, są one używane celowo jako ciało pętli.
    // Złą praktyką jest posiadanie efektów ubocznych poza pętlą:
    for (int i = 0; i < 3; Console.WriteLine(i), i++); // Niezgodny 
    // ...
}
```
Zgodne rozwiązanie:
```
void DoSomething()
{
}

void DoSomethingElse()
{
    Console.WriteLine("Hello, world!");
    // ...
    for (int i = 0; i < 3; i++)
    {
        Console.WriteLine(i);
     }
    // ...
}
```
Linijka: 46
![image](https://user-images.githubusercontent.com/48011447/144760396-e8063b7c-4562-4f8d-98cb-9cf6b44c9656.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
Drobny błąd, można szybko poprawić, zachęcam.
