### ISSUE TITLE
Nieużywane parametry metody należy usunąć

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#26]
Warning S1172. Usuń ten nieużywany parametr metody „operacja”.

Komunikat IDE0060 Usuń nieużywany parametr „operacja”.

Ta reguła oznacza nieużywane parametry. Wartość opcji określa, czy nieużywane parametry powinny być oflagowane tylko dla metod niepublicznych, czy dla metod publicznych i niepublicznych.

Ta reguła nie oznacza parametrów, które są nazwane symbolem odrzucania _. Ponadto reguła ignoruje parametry, które są nazwane symbolem odrzucenia, po którym następuje liczba całkowita, na przykład _1. To zachowanie zmniejsza szum ostrzegawczy dotyczący parametrów, które są potrzebne do spełnienia wymagań dotyczących podpisu, na przykład metody używanej jako delegat, parametru ze specjalnymi atrybutami lub parametru, którego wartość jest niejawnie dostępna w czasie wykonywania przez platformę, ale nie jest przywoływana w kodzie.

Niewykorzystane parametry wprowadzają w błąd. Niezależnie od wartości przekazanych do takich parametrów, zachowanie będzie takie samo.

Ta reguła powoduje problem, gdy prywatna metoda klasy/struktury przyjmuje parametr bez jego użycia.
Przykład kodu niezgodnego:
```
private void DoSomething(int a, int b) // „b” jest nieużywane
{
    Compute(a);
}

private void DoSomething2(int a) // wartość „a” nie jest używana
{
    a = 10;
    Compute(a);
}
```
Zgodne rozwiązanie:
```
private void DoSomething(int a)
{
    Compute(a);
}

private void DoSomething2()
{
    var a = 10;
    Compute(a);
}
```
Wyjątki:
Ta reguła nie powoduje żadnych problemów w następujących kontekstach:

- Parametr _this_ metod rozszerzających.
- Metody ozdobione atrybutami.
- Puste metody.
- Metody, które generują tylko _NotImplementedException_.
- Główne pliku _main_ metody.
- Metody _virtual, override_ (wirtualne, zastępujące).
- Implementacje interfejsu.

Linijka: 1084

![image](https://user-images.githubusercontent.com/48011447/144760622-f0b125d7-f7f0-4c4a-8007-2d240056c4dc.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
Po raz kolejny - zachęcam do refaktoryzacji kodu, pozbycia się byków i połowa problemów zostanie zamknięta.
