### ISSUE TITLE
Nieużywane prywatne typy lub członkowie powinni zostać usunięci

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#27]
Komunikat S1144. Usuń nieużywaną metodę prywatną „RemoveUnlessPoint”.

Remove unused private member (IDE0051)

Ta reguła oznacza nieużywane prywatne metody, pola, właściwości i zdarzenia, które nie mają odniesień do odczytu lub zapisu. Ta reguła nie ma powiązanej opcji stylu kodu.

Typy _private_ lub _internal_,  czy elementy _private_, które nigdy nie są wykonywane lub przywoływane, są martwym kodem: niepotrzebnym, niedziałającym kodem, który należy usunąć. Wyczyszczenie martwego kodu zmniejsza rozmiar utrzymywanej bazy kodu, ułatwiając zrozumienie programu i zapobiegając wprowadzaniu błędów.

Przykład kodu niezgodnego:
```
public class Foo
{
    private void UnusedPrivateMethod() {...} // Niezgodny

    private class UnusedClass {...} // Niezgodny
}
```
Zgodne rozwiązanie:
```
public class Foo
{
    public Foo()
    {
        UsedPrivateMethod();
    }

    private void UsedPrivateMethod()
    {
        var c = new UsedClass();
    }

    private class UsedClass {...}

```
Wyjątki:
Ta zasada nie powoduje problemów z:

- Pustymi konstruktorami
- Przypisanymi członkami
- Główną metodą _Main_ 
- Metodyami z podpisem procedury obsługi zdarzeń _void Foo(object, EventArgs)_, które są zadeklarowane w częściowej klasie
- Pusty Konstruktor serializacji typu z atrybutem _System.SerializableAttribute._
- Elementy wewnętrzne w zestawach, które mają atrybut _System.Runtime.CompilerServices.InternalsVisibleToAttribute_.

Linijka: 1176 Nigdy nie jest używana!
![image](https://user-images.githubusercontent.com/48011447/144760936-af32db6c-c91f-4ea9-8e25-a3a00b28f818.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
Skrócenie której funkcji warunkowej?
