### ISSUE TITLE
Usuń niepotrzebne przypisanie wartości

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#28]
Komunikat IDE0059 Niepotrzebne przypisanie wartości do 'arg2'.

Ta reguła oznacza niepotrzebne przypisania wartości. Na przykład:
```
int v = Compute(); // IDE0059: wartość zapisana do 'v' nigdy nie jest odczytywana, więc przypisanie do 'v' jest niepotrzebne.
v = Compute2();
```
Użytkownicy mogą wykonać jedną z następujących czynności, aby naprawić to naruszenie:

- Jeśli wyrażenie po prawej stronie przypisania nie ma efektów ubocznych, usuń wyrażenie lub całą instrukcję przypisania. Poprawia to wydajność, unikając niepotrzebnych obliczeń.
`int v = Compute2();`

- Jeśli wyrażenie po prawej stronie przypisania ma efekty uboczne, zastąp lewą stronę przypisania zmienną odrzuconą lub lokalną, która nigdy nie jest używana. Poprawia to przejrzystość kodu i wyraźny zamiar odrzucenia nieużywanej wartości. Opcja dla tej reguły dotyczy użycia odrzuconej lub nieużywanej zmiennej lokalnej.
```
_ = Compute();
int v = Compute2();
```
Linijki:
964, 965, 1046.
![image](https://user-images.githubusercontent.com/48011447/144761286-b5e704e2-13f5-4d12-a2c7-fa677ca2d78b.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
To słynne arg2, pojawiło się częściowo także w innym problemie.
