### ISSUE TITLE
Deklaracja zmiennej może być wbudowana

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#29]
Komunikat IDE0018. Variable declaration can be inlined.

Ta reguła stylu dotyczy tego, czy zmienne _out_ są deklarowane w wierszu, czy nie. Począwszy od C# 7, można zadeklarować zmienną out na liście argumentów wywołania metody, a nie w oddzielnej deklaracji zmiennej.
```
// csharp_style_inlined_variable_declaration = true
if (int.TryParse(value, out int i) {...}

// csharp_style_inlined_variable_declaration = false
int i;
if (int.TryParse(value, out i) {...}
```
Linijka: 964
![image](https://user-images.githubusercontent.com/48011447/144762081-9288bfa5-8515-4e8e-87be-944fbbcb23ad.png)

**Comment by haribo841** [comment]
Po poprawce bez zmian.

**Comment by astolowska** [comment]
Polecam takie rozwiązania, szczególnie, gdy ze zmienną nie dzieje się potem za dużo.
