### ISSUE TITLE
„IEnumerable” LINQ powinny być uproszczone

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#30]
WarningS2971. Zamiast tego użyj właściwości „Count”.

W interesie czytelności kod, który można uprościć, powinien zostać uproszczony. W tym celu istnieje kilka sposobów uproszczenia zintegrowanych zapytań językowych IEnumerable (LINQ)

- Użyj _OfType_ zamiast używać _Select_ z _as_ do wpisywania elementów rzutowania, a następnie sprawdzania wartości _null_ w wyrażeniu zapytania, aby wybrać elementy na podstawie typu.
- Użyj _OfType_ zamiast używania _Where_ i operatora _is_, po którym następuje rzutowanie w _Select_
- Użyj wyrażenia w _Any_ zamiast _Where(element => [expression]).Any()._
- Użyj _Count_ zamiast _Count()_, gdy jest to możliwe.
- Nie wywołuj _ToArray()_ ani _ToList()_ w środku łańcucha zapytań.

Korzystanie z _EntityFramework_ może wymagać wymuszania ocen klientów. Takie zapytania powinny używać _AsEnumerable()_ zamiast _ToArray()_ lub _ToList()_ w środku łańcucha zapytań.

Przykład kodu niezgodnego:
```
seq1.Select(element => element as T).Any(element => element != null);  // Niezgodny; użyj OfType
seq2.Select(element => element as T).Any(element => element != null && CheckCondition(element));  // Niezgodny; użyj OfType
seq3.Where(element => element is T).Select(element => element as T); // Niezgodny; użyj OfType
seq4.Where(element => element is T).Select(element => (T)element); // Niezgodny; użyj OfType
seq5.Where(element => [expression]).Any();  // Niezgodny; użyj Any([expression])

var num = seq6.Count(); // Niezgodny
var arr = seq.ToList().ToArray(); //Niezgodny
var count = seq.ToList().Count(x=>[condition]); //Niezgodny
```
Zgodne rozwiązanie:
```
seq1.OfType<T>().Any();
seq2.OfType<T>().Any(element => CheckCondition(element));
seq3.OfType<T>();
seq4.OfType<T>();
seq5.Any(element => [expression])

var num = seq6.Count;
var arr = seq.ToArray();
var count = seq.Count(x=>[condition]);
```
Linijka: 111
`int usersCount = usersList.Count();`

**Comment by astolowska** [comment]
Rzeczywiście, nie zmienia to dużo, chętnie poprawię!
