### ISSUE TITLE
Metody nie powinny mieć identycznych implementacji

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#31]
Warning S4144. Zaktualizuj tę metodę, aby jej implementacja nie była identyczna z 'ButtonKalkulator'.

Generalnie mamy możliwość wejścia w kalkulator podstawowy w dwóch miejscach. Czy wejście na pasku powinno być wyłączone, czy ma się odwoływać do drugiego? Bo przejście do podstawowego kalkulatora, a nie okna wyboru to raczej błąd.
![image](https://user-images.githubusercontent.com/48011447/144769120-18cd0f6b-c9c9-46d1-be49-038c4e50727f.png)

Gdy dwie metody mają tę samą implementację, albo był to błąd — zaplanowano coś innego — albo powielanie było celowe, ale może to być mylące dla innych. W tym drugim przypadku jedna implementacja powinna odwoływać się do drugiej.

Przykład kodu niezgodnego:
```
private const string CODE = "bounteous";
private int callCount = 0;

public string GetCode()
{
  callCount++;
  return CODE;
}

public string GetName()  // Niezgodne
{
  callCount++;
  return CODE;
}
```
Zgodne rozwiązanie:
```
private const string CODE = "bounteous";
private int callCount = 0;

public string GetCode()
{
  callCount++;
  return CODE;
}

public string GetName()
{
  return GetCode();
}
```
Wyjątki:
Puste metody, metody z tylko jednym wierszem kodu i metody o tej samej nazwie (przeciążenie) są ignorowane.

Linijki: 32 robi to samo co 63

A może się mylę i chodzi tu o zmiane refaktoryzacji sygnatury metody?

**Comment by astolowska** [comment]
Jest to pozostałość starego rozwiązania, co do aktualizacji którego nie było jeszcze zgody - ja uważam, że jak najbardziej można zmienić ścieżkę.
