### ISSUE TITLE
Gdy zjesz cały RAM

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#32]
Kiedy Abituria wykorzysta dostępną pamieć RAM, wysypie się na ostatniej funkcji.

Jako, że można otwierać nieskończenie wiele okien, będzie to wymagało nieskończonej ilości pamięci.

W moim przypadku po niecałych 10 minutach intensywnego otwierania okien (ok. 5k) i zużycia 8 GB RAMu, 
udało mi się wysypać w ten sposób program.

System.OutOfMemoryException
  HResult=0x8007000E
  Message=Insufficient memory to continue the execution of the program.
  Source=PresentationCore
  StackTrace:
   at System.Windows.Media.Composition.DUCE.Channel.CreateOrAddRefOnChannel(Object instance, ResourceHandle& handle, ResourceType resourceType)

  This exception was originally thrown at this call stack:
    System.Windows.Media.Composition.DUCE.Channel.CreateOrAddRefOnChannel(object, ref System.Windows.Media.Composition.DUCE.ResourceHandle, System.Windows.Media.Composition.DUCE.ResourceType)

![image](https://user-images.githubusercontent.com/48011447/145729624-a81c14b3-74ac-4038-99f6-3322cc303ab3.png)

![image](https://user-images.githubusercontent.com/48011447/145729534-5230b38c-5665-43a8-a245-e9691004044d.png)

**Comment by astolowska** [comment]
Jedną z opcji, jaką widzę jest ograniczenie liczby otwieranych okien. Próbowałam to kiedyś zrobić, ale nie do końca jest to łatwe.

**Comment by astolowska** [comment]
co zrobisz, nic nie zrobisz
![image](https://user-images.githubusercontent.com/48011791/148707168-9d0d674d-7a0d-41b4-b37a-378e28e7a03d.png)
