### ISSUE TITLE
Zerowanie znakiem =

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#6]
Gdy po wykonaniu działania i otrzymaniu wyniku kliknie się znak '=' zawsze otrzymujemy zero.

**Comment by Filippo1998r** [comment]
No tak, teraz jak patrzę to rozumiem o co chodzi. Zmieniłem tylko pod kątem przepisania liczby z dołu na górę. Zostawiłem to, bo znak '=' był wcześniej jedyną możliwością zerowania/czyszczenia pól. Nie było to dla mnie błędne, ani nawet bezsensowne, ale to dla mnie (kodera ;) ). Jutro to zmienię

**Comment by astolowska** [comment]
Nie zeruje wyniku, ale nie powtarza też poprzedniego działania. Znaku równości można nadużywać, ale nie zadzieje się nic.

**Comment by Filippo1998r** [comment]
> 

Tak jest, taki był zamysł, tak miało działać, tak też działa mój kalkulator w telefonie na którym też się wzoruję.
