### ISSUE TITLE
1/∞

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#7]
Dzielenie pewnej liczby (powiedzmy x) przez inną (powiedzmy y) oznacza po prostu rozbicie x na y równych części.

W tym przypadku 1 należy podzielić na nieskończoną liczbę równych części. Oczywiście nieskończoność nie jest liczbą (to tylko idea, z którą nie można sobie poradzić) i ten podział nie ma sensu.

Na podstawie analogii możemy powiedzieć, że nieskończoność jest naprawdę duża (nie ma wyobrażenia). Tak więc, jeśli 1 ma być dzielona nieskończenie wiele razy, (dla naszej wygody) dzielimy 1 przez liczbę zbliżającą się do nieskończoności. Jeśli to zrobimy, otrzymamy wynik zbliżony do 0 (nie dokładnie 0).

Jaka jest wartość 1/∞ ?

Cóż, nie wiemy. Więc powinno być tak jak z dzieleniem przez 0.

Jaka jest wartość granicy x zmierzającej do nieskończoności, 1/x?

Dążący do 0. (dążący do 0 od lewej, tj. < 0, jeśli x ma tendencję do ujemnej nieskończoności, o której mowa) i (dążący do 0 od prawej, tj. > 0, jeśli x ma tendencję do dodatniej nieskończoności). Ale tutaj nie liczymy granic.

PS Absolutna nieskończoność to pojęcie abstrakcyjne, takie jak Filip. Czy „1/Filip=?” ma sens?

**Comment by Filippo1998r** [comment]
Odnośnie komentarza Aleksandry już się tak nie dzieje. Odnośnie tematu 1/∞ to internet (interauci, fora itd.) jest w tej kwestii podzielony, ja też zostałem przekonany o prawidłowości równania 1/∞=0 choćby na zasadzie działania zaokrągleń w komputerze. Taki nasze procesory podają wynik więc togo bym się trzymał.
