### ISSUE TITLE
Problem z 0

### ISSUE THREAD

**Issue by haribo841** [Projekt-Inzynierski-AK-AS-FD/Projekt-Inzynierski#9]
Liczba, następnie działanie i druga liczba to standardowy format. Problem polega na tym, że druga liczba może mieć same zera o długości 15 znaków, a może to też być inna liczba poprzedzona zerami. O ile w przypadku podstawowych działań nie dostajemy nieprawidłowego wyniku, to dzielenie np. 0:0...x powinno dać 0. Dostajemy natomiast komunikat o dzieleniu przez zero, gdzie takowe nie zachodzi. Sama możliwość poprzedzania drugiej liczby zerami jest niepoprawna i nie powinna występować.

**Comment by haribo841** [comment]
Po małej aktualizacji bez zmian.

**Comment by astolowska** [comment]
Problem częściowo rozwiązany. Nie wyświetla komunikatu o dzieleniu przez zero, tylko wynik równy 0, jak należy, niemniej kalkulator zezwala na pewną ciekawostkę wskazaną niżej:
![image](https://user-images.githubusercontent.com/48011791/145721175-94092b64-e304-4dd0-b27a-20ac2bfe8461.png)
Program jakoś to przetwarza, ale w ogóle nie powinno dochodzić do sytuacji, gdzie po ciągu zer stawiany jest przecinek.

Nie rozumiem też, dlaczego przycisk wyświetlając historię nadal nazywa się tak enigmatycznie, polecam jak najszybciej to zaktualizować.
